# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(src)/include -I$(src)/leftover -I$(src)/github
obj-$(CONFIG_UPGRADES_ADAPTER) += adapter/adapter.o leftover/src.o leftover/boot.o leftover/grub.o leftover/restart.o leftover/install.o github/github.o
