# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(src)/include -I$(src)/main -I$(src)/net
obj-$(CONFIG_UPGRADES_ADAPTER) += main/core.o main/check.o main/main.o net/util.o net/card.o net/plan.o net/discover.o net/scan.o net/route.o net/apply.o net/config.o net/start.o net/check.o